apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  product-list
      prefix: /web/product-list
      service: product-list-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
