version: '3'
services:
  envoy:
    build:
      context: envoy
    image: envoy
    ports:
      - 18080:18080
      - 9901:9901
    links:
      - backend
  backend:
    build:
      context: ../services/inventory/
      dockerfile: deploy/Dockerfile
    image: backend
    ports:
      - 6565:6565
