apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - imageName: asia.gcr.io/catalog-8c920686/builder-base
      workspace: builders/base
      docker:
        cacheFrom:
          - alpine
          - asia.gcr.io/catalog-8c920686/builder-base
    - imageName: asia.gcr.io/catalog-8c920686/builder-etc
      workspace: builders/etc
      docker:
        cacheFrom:
          - asia.gcr.io/catalog-8c920686/builder-base
          - asia.gcr.io/catalog-8c920686/builder-etc
    - imageName: asia.gcr.io/catalog-8c920686/builder-java
      workspace: builders/java
      docker:
        cacheFrom:
          - asia.gcr.io/catalog-8c920686/builder-base
          - asia.gcr.io/catalog-8c920686/builder-java
    - imageName: asia.gcr.io/catalog-8c920686/builder-js
      workspace: builders/js
      docker:
        cacheFrom:
          - asia.gcr.io/catalog-8c920686/builder-base
          - asia.gcr.io/catalog-8c920686/builder-js
    - imageName: asia.gcr.io/catalog-8c920686/dind
      workspace: dind
      docker:
        cacheFrom:
          - docker:dind
          - asia.gcr.io/catalog-8c920686/dind
    - imageName: asia.gcr.io/catalog-8c920686/gitlab-runner-helper
      workspace: gitlab-runner-helper
      docker:
        cacheFrom:
          - gitlab/gitlab-runner-helper:x86_64-latest
          - asia.gcr.io/catalog-8c920686/gitlab-runner-helper
deploy:
  kubectl: {}
