apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: asia.gcr.io/catalog-8c920686/cockroachdb
      workspace: deploy
      docker: {}
#        cacheFrom:
#          - cockroachdb/cockroach
#          - asia.gcr.io/catalog-8c920686/cockroachdb
deploy:
  kustomize:
    kustomizePath: deploy
