apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 26258
      targetPort: http
    - name: jdbc
      port: 26257
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: mgmt-svc
  annotations:
    # Use this annotation in addition to the actual publishNotReadyAddresses
    # field below because the annotation will stop being respected soon but the
    # field is broken in some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 26257
      targetPort: grpc
