apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  inventory
      prefix: /api/inventory/
      service: inventory-svc
      grpc: true
      cors:
        origins: "*"
        methods: GET, PUT, DELETE, POST, OPTIONS
        headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
        credentials: true
        exposed_headers: grpc-status,grpc-message
        max_age: "1728000"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
