apiVersion: v1
kind: Service
metadata:
  name: svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  inventory
      prefix: /api/inventory/
      service: inventory-svc
      grpc: true
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 80
      targetPort: grpc
