apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: asia.gcr.io/catalog-8c920686/web-ui
      docker:
        dockerfilePath: deploy/Dockerfile
#        cacheFrom:
#          - nginx:alpine
#          - asia.gcr.io/catalog-8c920686/web-ui
deploy:
  kustomize:
    kustomizePath: deploy
