apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - imageName: asia.gcr.io/catalog-8c920686/product-list
      docker:
        dockerfilePath: deploy/Dockerfile
#        cacheFrom:
#          - nginx:alpine
#          - asia.gcr.io/catalog-8c920686/product-list
deploy:
  kustomize:
    kustomizePath: deploy
