concurrent = 10

[[runners]]
  name = "catalog-runner"
  url = "https://gitlab.com/"
  token = "_TOKEN_"
  executor = "kubernetes"
  [runners.kubernetes]
    service_account = "gitlab-runner-executor-sa"
    namespace = "catalog-ops"
    image = "alpine"
    cpu_request = "256m"
    memory_request = "256Mi"
    cpu_limit = "256m"
    memory_limit = "128Mi"
    service_cpu_request =  "128m"
    service_memory_request = "64Mi"
    service_cpu_limit = "128m"
    service_memory_limit = "64Mi"
    helper_cpu_request =  "128m"
    helper_memory_request = "64Mi"
    helper_cpu_limit = "64m"
    helper_memory_limit = "32Mi"
    pull_policy = "always"
    helper_image = "asia.gcr.io/catalog-8c920686/gitlab-runner-helper:latest"
    terminationGracePeriodSeconds = 30
    privileged = true
  [runners.cache]
    Type = "s3"
    ServerAddress = "minio-svc"
    Insecure = true
    AccessKey = "catalog"
    SecretKey = "catalog"
    BucketName = "gitlab-runner-cache"
    Shared = true
