# Kustomize interpolation doesn't work properly with ClusterRoleBinding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executor-binding
  namespace: catalog-ops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-executor-sa
    namespace: catalog-ops
