apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-role
subjects:
  - kind: ServiceAccount
    name: runner-sa
